import { prisma } from "./prisma";
import { cache } from "react";

export type Settings = Record<string, string | null>;

export const getSettings = cache(async (): Promise<Settings> => {
  try {
    const settings = await prisma.siteSetting.findMany();
    return settings.reduce((acc, s) => {
      acc[s.key] = s.value;
      return acc;
    }, {} as Settings);
  } catch {
    return {};
  }
});

export async function getSetting(key: string): Promise<string | null> {
  const settings = await getSettings();
  return settings[key] ?? null;
}

export const DEFAULT_SETTINGS: Record<string, string> = {
  // General
  site_name: "ESAMIR",
  site_tagline: "Lüks Halı & İç Mimarlık",
  site_description: "ESAMIR, seçkin İran halısı koleksiyonu ve iç mimarlık danışmanlığı sunar.",
  site_language: "tr",
  logo: "",
  favicon: "",
  // Contact
  phone: "+90 532 000 00 00",
  whatsapp: "+905320000000",
  email: "info@esamir.com",
  address: "İstanbul, Türkiye",
  working_hours: "Pazartesi - Cumartesi: 09:00 - 18:00",
  working_hours_weekend: "",
  // Social
  instagram: "",
  facebook: "",
  pinterest: "",
  youtube: "",
  twitter: "",
  linkedin: "",
  tiktok: "",
  // Maps
  google_maps_embed: "",
  google_maps_url: "",
  latitude: "",
  longitude: "",
  map_title: "Showroom Konumumuz",
  map_description: "",
  map_width: "800px",
  map_height: "600px",
  // Google Review
  google_review_link: "",
  google_review_title: "Google'da Bizi Değerlendirin",
  google_review_description: "Deneyiminizi paylaşarak diğer müşterilere yardımcı olun.",
  google_review_button: "Değerlendirme Yap",
  google_review_show: "true",
  google_review_show_home: "true",
  google_review_show_contact: "true",
  // SEO
  seo_title: "ESAMIR | Lüks Halı & İç Mimarlık",
  seo_description: "ESAMIR, seçkin İran halısı koleksiyonu, premium aksesuarlar ve profesyonel iç mimarlık danışmanlığı sunan prestijli bir yaşam alanları markasıdır.",
  seo_og_image: "",
  seo_robots: "index,follow",
  // Header
  header_announcement: "",
  header_announcement_active: "false",
  header_cta_label: "Koleksiyonu Keşfet",
  header_cta_href: "/kategoriler",
  // Hero
  hero_title: "Yaşam Alanlarına Zarafet Katın",
  hero_subtitle: "Premium Koleksiyon",
  hero_description: "Seçkin İran halısı koleksiyonu, premium aksesuarlar ve profesyonel iç mimarlık danışmanlığı ile yaşam alanlarınızı baştan tasarlıyoruz.",
  hero_cta_label: "Koleksiyonu Keşfet",
  hero_cta_href: "/kategoriler",
  hero_image: "",
  // Footer
  footer_text: "ESAMIR © 2024. Tüm hakları saklıdır.",
  footer_tagline: "Lüks Halı & İç Mimarlık",
  footer_col1_title: "Koleksiyon",
  footer_col2_title: "Kurumsal",
  footer_col3_title: "İletişim",
  footer_bottom_text: "",
  // WhatsApp CTA
  whatsapp_cta_title: "Özel Tasarım mı İstiyorsunuz?",
  whatsapp_cta_description: "Uzman ekibimiz ile WhatsApp üzerinden iletişime geçin.",
  whatsapp_cta_button: "WhatsApp'tan Yazın",
  // Blog
  blog_show_homepage: "true",
  // About section
  about_title: "ESAMIR Hakkında",
  about_description: "",
  // Interior section
  interior_label: "İç Mimarlık",
  interior_title: "Mekanı Sanata",
  interior_title_italic: "Dönüştürüyoruz",
  interior_text1: "20 yılı aşkın deneyimimizle iç mimarlık alanında sunduğumuz bütüncül yaklaşım, yaşam alanlarınızı yalnızca güzel değil, aynı zamanda işlevsel ve ruhunuzu yansıtan mekânlara dönüştürüyor.",
  interior_text2: "İran halısının eşsiz dokuma geleneğini modern iç mimarlık anlayışıyla harmanlayarak; her parçanın, her rengin ve her dokunun yaşam alanınızda anlamlı bir yer bulmasını sağlıyoruz.",
  interior_stat1_number: "500+",
  interior_stat1_label: "Tamamlanan Proje",
  interior_stat2_number: "20+",
  interior_stat2_label: "Yıllık Deneyim",
  interior_stat3_number: "1000+",
  interior_stat3_label: "Ürün Çeşidi",
  interior_stat4_number: "98%",
  interior_stat4_label: "Müşteri Memnuniyeti",
  interior_cta_text: "Yaklaşımımızı Keşfedin",
  interior_cta_url: "/ic-mimarlik",
  interior_image1: "/images/interior-1.jpg",
  interior_image2: "/images/interior-2.jpg",
  // About page
  about_hero_overline: "Hikayemiz",
  about_hero_title: "Hakkımızda",
  about_hero_bg: "",
  about_story_overline: "ESAMIR",
  about_story_title: "Zarafeti Yaşam Alanlarına Taşıyoruz",
  about_story_text1: "ESAMIR, İran'ın köklü halı dokuma geleneğine derin saygı duyarak kurulmuş, premium yaşam alanı çözümleri sunan bir markadır. 20 yılı aşkın deneyimimizle, her evin ve her mekanın ruhuna uygun özgün koleksiyonlar sunmaktayız.",
  about_story_text2: "Adımız Farsça'da \"güvenli, huzurlu\" anlamına gelen ESAMIR, bu ismin özüne sadık kalarak müşterilerimize yalnızca ürün değil; güven, estetik ve kalıcı değer sunmayı hedefler.",
  about_story_text3: "Her halı bir sanat eseridir; her aksesuar bir hikaye anlatır. Biz bu hikayeleri sizin evinizde yaşatmak için buradayız.",
  about_story_image: "",
  about_philosophy_overline: "İç Mimarlık Felsefemiz",
  about_philosophy_title: "Mekan, Anlam Kazanır",
  about_philosophy_desc: "İç mimarlık yaklaşımımız, mekânın yalnızca fiziksel boyutunu değil, duygusal ve estetik katmanlarını da göz önünde bulundurur.",
  about_philosophy_item1_title: "Kişiselleştirilmiş Tasarım",
  about_philosophy_item1_desc: "Her müşterimizin yaşam tarzı, beğeni ve ihtiyaçlarına özgü çözümler geliştiriyoruz.",
  about_philosophy_item1_num: "01",
  about_philosophy_item2_title: "Kalıcı Estetik",
  about_philosophy_item2_desc: "Moda değil; zamansız, kalıcı ve değer katan estetik seçimler yapıyoruz.",
  about_philosophy_item2_num: "02",
  about_philosophy_item3_title: "Kusursuz Harmoni",
  about_philosophy_item3_desc: "Halı, aksesuar ve mobilya arasındaki dengeyi titizlikle kurarak bütünlük yaratıyoruz.",
  about_philosophy_item3_num: "03",
  about_heritage_overline: "İran Halısı Geleneği",
  about_heritage_title: "Asırların Birikimiyle Dokunan Sanat",
  about_heritage_text1: "İran halısı, binlerce yıllık bir dokuma geleneğinin ve kültürel zenginliğin ürünüdür. Her halı; rengiyle, deseniyle ve malzeme kalitesiyle bir medeniyetin izlerini taşır.",
  about_heritage_text2: "Koleksiyonumuzdaki her parça, İran'ın farklı bölgelerindeki usta ellerden çıkmıştır. İpek, yün ve özel karışım ipliklerle dokunan bu halılar; hem dekoratif hem de uzun ömürlü yatırım değeri taşır.",
  about_heritage_img1: "",
  about_heritage_img2: "",
  about_stat1_number: "500+",
  about_stat1_label: "Tamamlanan Proje",
  about_stat2_number: "20+",
  about_stat2_label: "Yıllık Deneyim",
  about_stat3_number: "1000+",
  about_stat3_label: "Ürün Çeşidi",
  about_stat4_number: "98%",
  about_stat4_label: "Müşteri Memnuniyeti",
  about_cta_title: "Birlikte Yaratın",
  about_cta_desc: "Projeniz için ücretsiz danışmanlık ve showroom ziyareti için iletişime geçin.",
  about_cta_primary_label: "İletişime Geçin",
  about_cta_primary_href: "/iletisim",
  about_cta_secondary_label: "Koleksiyonu İncele",
  about_cta_secondary_href: "/kategoriler",
  // Interior page
  interior_page_hero_overline: "Hizmetlerimiz",
  interior_page_hero_title: "İç Mimarlık &",
  interior_page_hero_title_italic: "Tasarım Danışmanlığı",
  interior_page_hero_desc: "Yaşam alanlarınızı sizin için tasarlıyor, halı ve aksesuar seçimlerinden uygulama sürecine kadar yanınızda oluyoruz.",
  interior_page_hero_bg: "",
  interior_page_approach_overline: "Yaklaşımımız",
  interior_page_approach_title: "Her Mekan Bir Kimlik Taşır",
  interior_page_approach_text1: "İç mimarlık yaklaşımımız, mekânın yalnızca fiziksel boyutunu değil, duygusal ve estetik katmanlarını da göz önünde bulundurur. Her projeye özgün bir bakış açısıyla yaklaşıyor, yaşam alanlarınızı kişiliğinizi yansıtan mekânlara dönüştürüyoruz.",
  interior_page_approach_text2: "İran halısının eşsiz dokuma geleneğini modern iç mimarlık anlayışıyla harmanlayarak; her parçanın, her rengin ve her dokunun yaşam alanınızda anlamlı bir yer bulmasını sağlıyoruz.",
  interior_page_approach_features: "Kişiye özel tasarım konsepti\nÜcretsiz ilk danışmanlık görüşmesi\n3D görselleştirme imkânı\nYerinde uygulama desteği",
  interior_page_approach_cta: "Danışmanlık Talep Et",
  interior_page_approach_cta_url: "/iletisim",
  interior_page_approach_img1: "",
  interior_page_approach_img2: "",
  interior_page_services_overline: "Neler Yapıyoruz",
  interior_page_services_title: "Hizmetlerimiz",
  interior_page_service1_title: "Konsept Tasarım",
  interior_page_service1_desc: "Yaşam tarzınıza ve beğenilerinize uygun özgün konsept tasarımları geliştiriyoruz.",
  interior_page_service1_icon: "01",
  interior_page_service2_title: "Halı Seçimi",
  interior_page_service2_desc: "Geniş koleksiyonumuzdan mekanınıza en uygun halıları seçmenizde rehberlik ediyoruz.",
  interior_page_service2_icon: "02",
  interior_page_service3_title: "Renk Danışmanlığı",
  interior_page_service3_desc: "Mekanınızın rengini ve atmosferini belirleyen renk paletleri oluşturuyoruz.",
  interior_page_service3_icon: "03",
  interior_page_service4_title: "Mobilya Uyumu",
  interior_page_service4_desc: "Halı ve mobilya uyumunu sağlayarak bütünlüklü mekanlar yaratıyoruz.",
  interior_page_service4_icon: "04",
  interior_page_service5_title: "Uygulama Desteği",
  interior_page_service5_desc: "Tasarımın hayata geçirilmesi sürecinde yerinde destek sağlıyoruz.",
  interior_page_service5_icon: "05",
  interior_page_service6_title: "Sonrası Takip",
  interior_page_service6_desc: "Proje tamamlandıktan sonra da bakım ve düzenleme konusunda yanınızdayız.",
  interior_page_service6_icon: "06",
  interior_page_process_overline: "Nasıl Çalışırız",
  interior_page_process_title: "Süreç",
  interior_page_step1_title: "İlk Görüşme",
  interior_page_step1_desc: "İhtiyaçlarınızı ve beklentilerinizi dinliyor, mekanınızı inceliyoruz.",
  interior_page_step2_title: "Konsept Geliştirme",
  interior_page_step2_desc: "Size özel tasarım konsepti ve renk paleti oluşturuyoruz.",
  interior_page_step3_title: "Ürün Seçimi",
  interior_page_step3_desc: "Koleksiyonumuzdan en uygun halı ve aksesuarları belirliyoruz.",
  interior_page_step4_title: "Sunum ve Onay",
  interior_page_step4_desc: "3D görsellerle tasarımı sunuyor, geri bildirimlerinizi alıyoruz.",
  interior_page_step5_title: "Uygulama",
  interior_page_step5_desc: "Onaylanan tasarımı profesyonel ekibimizle hayata geçiriyoruz.",
  interior_page_cta_title: "Projenizi Konuşalım",
  interior_page_cta_desc: "Ücretsiz danışmanlık görüşmesi için bizimle iletişime geçin.",
  interior_page_cta_button: "İletişime Geçin",
  interior_page_cta_url: "/iletisim",
  
  // E-commerce Platform Links (Site-wide)
  ecommerce_trendyol_url: "",
  ecommerce_hepsiburada_url: "",
  ecommerce_shopier_url: "",
  ecommerce_show_in_footer: "true",
};
