FROM node:20-alpine

RUN apk add --no-cache openssl

WORKDIR /app

COPY package.json package-lock.json* ./
COPY prisma ./prisma
RUN npm ci

RUN npx prisma generate

COPY . .

CMD sh -c "npx prisma migrate deploy && npm run db:seed"
